Repository grm34/archboot, pull requests merged in 2020-05, with the labels that each got.

#210 Updates installation description
  README.md
  archboot
Labels: ✚ update

#211 Updates exit message
  archboot
Labels: ✚ update

#212 Updates 'prevent running script from repository folder'
  archboot
Labels: ⚠️ potential bug, ✔️ fixed, ✚ update

#213 Updates project templates
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
  archboot
Labels: ✚ update

#214 Updates contributing url
  README.md
Labels: ✚ update

#215 Prevents valid language and load keyboard table
  .gitignore
  archboot
Labels: 👑 implemented, 🙏 feature request

#216 Adds --keyboard option (run loadkeys on start)
  README.md
  STATS.md
  archboot
Labels: ✚ update, 👑 implemented, 🙏 feature request

#217 Updates german language
  locale/german
Labels: ✚ update, 🔒 enhancement

#218 Adds code of conduct
  .github/CODE_OF_CONDUCT.md
  .gitignore
  locale/german
Labels: 🔒 enhancement

#219 Adds language warning
  README.md
  archboot
Labels: 🔒 enhancement

#220 Fix --help option processing
  README.md
  archboot
Labels: ⚠️ potential bug, ✔️ fixed

#221 Updates official documentation
  README.md
Labels: ✚ update

#222 Adds some 'break' in for loops to increase process
  archboot
  src/arch/firmware
  src/arch/user
Labels: 🔒 enhancement

#223 Adds minor changes
  STATS.md
  src/arch/gpu_driver
  src/arch/user
Labels: 🔒 enhancement

#224 Adds language code when --keyboard specified
  STATS.md
  archboot
  locale/english
  locale/french
  locale/german
  src/arch/base
  src/arch/user
  src/conf/language
  src/conf/timezone
Labels: 🔒 enhancement

#225 Updates keyboard layout usage
  README.md
Labels: ✚ update

#226 Updates installer options
  README.md
Labels: ✚ update

#227 Fix grep ident error
  archboot
Labels: ⚠️ potential bug, ✔️ fixed

#228 Updates language processing comments
  STATS.md
  archboot
Labels: ✚ update

#229 Updates installer copyright ©
  STATS.md
  archboot
  locale/english
  locale/french
  locale/german
  src/apps/desktop_apps
  src/apps/display_apps
  src/apps/gpu_apps
  src/apps/system_apps
  src/arch/base
  src/arch/bootloader
  src/arch/desktop
  src/arch/display
  src/arch/firmware
  src/arch/gpu_driver
  src/arch/mirrorlist
  src/arch/mounting
  src/arch/partitioning
  src/arch/user
Labels: ✚ update

#230 Updates options description
  README.md
Labels: ✚ update

#231 Updates wiki links
  README.md
Labels: ✚ update

#232 Better way to handle keyboard layout
  README.md
  STATS.md
  archboot
  src/arch/user
Labels: 🔒 enhancement

#233 Updates german language
  locale/german
Labels: ✚ update

#234 Updates to v3.0.0
  README.md
  STATS.md
  archboot
  locale/english
  locale/french
  locale/german
  src/arch/base
  src/arch/bootloader
  src/arch/firmware
  src/arch/gpu_driver
  src/arch/mirrorlist
  src/arch/user
Labels: ✚ update, 🔒 enhancement, 🚨 major update

#235 Updates project license
  LICENSE
  archboot
Labels: ✚ update

#236 Adds LVM and LUKS support
  .github/ISSUE_TEMPLATE/update.md
  STATS.md
  archboot
  locale/english
  locale/french
  locale/german
  src/apps/system_apps
  src/arch/base
  src/arch/bootloader
  src/arch/desktop
  src/arch/display
  src/arch/firmware
  src/arch/gpu_driver
  src/arch/mirrorlist
  src/arch/mounting
  src/arch/partitioning
  src/arch/user
Labels: ⚠️ potential bug, 🙏 feature request, 🚨 major update

#238 Updates german
  locale/german
Labels: ✚ update

#240 Updates from master
  archboot
Labels: ✚ update

#239 Adds LVM on LUKS
  archboot
  locale/english
  locale/french
  locale/german
  src/arch/base
  src/arch/partitioning
  src/arch/user
Labels: ✔️ fixed, 🚨 major update, 🚫 bug

#241 Command output to array
  STATS.md
  src/arch/partitioning
Labels: ✔️ fixed, 🚫 bug

#242 Fix invalid comment
  src/arch/partitioning
Labels: ⚠️ potential bug, ✔️ fixed

#243 Minor changes
  archboot
  locale/english
  locale/french
  locale/german
  src/arch/base
  src/arch/bootloader
  src/arch/mirrorlist
  src/arch/partitioning
  src/arch/user
Labels: 🔒 enhancement

#244 Improve user inputs log
  STATS.md
  archboot
Labels: 🔒 enhancement

#246 Updates GPU Drivers
  README.md
  STATS.md
  archboot
  locale/english
  locale/french
  locale/german
  src/apps/gpu_apps
  src/apps/system_apps
  src/arch/base
  src/arch/bootloader
  src/arch/desktop
  src/arch/display
  src/arch/firmware
  src/arch/gpu_driver
  src/arch/mirrorlist
  src/arch/partitioning
  src/arch/user
Labels: ✚ update, 🔒 enhancement, 🧑‍🔧 need beta testers

#248 LVM on LUKS tests
  STATS.md
  archboot
  src/arch/partitioning
Labels: 🔒 enhancement

#249 Updates project stats
  STATS.md
Labels: 🔒 enhancement

#250 Improve project stats
  STATS.md
Labels: 🔒 enhancement

#251 Updates markdown style
  README.md
Labels: ✚ update

#252 Adds more AUR Helpers
  STATS.md
  src/arch/base
  src/arch/user
Labels: 👑 implemented, 🔒 enhancement

#253 Adds AUR Helper wiki page
  README.md
Labels: ✚ update

#254 Adds Hardware Video Acceleration utils
  src/apps/gpu_apps
  src/arch/gpu_driver
Labels: 🔒 enhancement

#255 Updates VDPAU nvidia proprietary
  README.md
  src/apps/gpu_apps
Labels: ✚ update

#256 Adds ipinfo API token authentication
  archboot
  src/arch/mirrorlist
  src/arch/partitioning
Labels: 🔒 enhancement

#257 Adds secure HTTPS connection for ipinfo API
  src/arch/mirrorlist
Labels: 🔒 enhancement

#258 Fix arch-chroot error
  archboot
Labels: ✔️ fixed, 🚫 bug

#259 Allow decimals for partition sizes
  STATS.md
  archboot
  src/arch/partitioning
Labels: 🔒 enhancement
